import type { Lead, Activity, Profile } from "@/types"

export const MOCK_PROFILES: Profile[] = [
  {
    id: "profile-1",
    name: "Ana Souza",
    email: "ana@pipeflow.com",
    avatar_url: null,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "profile-2",
    name: "Carlos Lima",
    email: "carlos@pipeflow.com",
    avatar_url: null,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "profile-3",
    name: "Beatriz Rocha",
    email: "bea@pipeflow.com",
    avatar_url: null,
    created_at: "2024-01-01T00:00:00Z",
  },
]

export const MOCK_LEADS: Lead[] = [
  {
    id: "lead-1",
    workspace_id: "ws-1",
    name: "Rafael Mendes",
    email: "rafael@techcorp.com",
    phone: "(11) 98765-4321",
    company: "TechCorp",
    role: "CEO",
    status: "new",
    owner_id: "profile-1",
    created_at: "2024-03-10T09:00:00Z",
    owner: MOCK_PROFILES[0],
  },
  {
    id: "lead-2",
    workspace_id: "ws-1",
    name: "Juliana Torres",
    email: "juliana@startupx.io",
    phone: "(21) 99887-6655",
    company: "StartupX",
    role: "CTO",
    status: "contact",
    owner_id: "profile-2",
    created_at: "2024-03-12T10:30:00Z",
    owner: MOCK_PROFILES[1],
  },
  {
    id: "lead-3",
    workspace_id: "ws-1",
    name: "Marcos Pereira",
    email: "marcos@consultoria.com.br",
    phone: "(31) 97654-3210",
    company: "Consultoria MP",
    role: "Diretor Comercial",
    status: "proposal",
    owner_id: "profile-1",
    created_at: "2024-03-14T14:00:00Z",
    owner: MOCK_PROFILES[0],
  },
  {
    id: "lead-4",
    workspace_id: "ws-1",
    name: "Fernanda Costa",
    email: "fernanda@agenciafoco.com",
    phone: "(41) 98877-5544",
    company: "Agência Foco",
    role: "Sócia-Fundadora",
    status: "negotiation",
    owner_id: "profile-3",
    created_at: "2024-03-15T11:00:00Z",
    owner: MOCK_PROFILES[2],
  },
  {
    id: "lead-5",
    workspace_id: "ws-1",
    name: "Diego Alves",
    email: "diego@logisticabr.com",
    phone: "(51) 96655-4433",
    company: "LogísticaBR",
    role: "Gerente de TI",
    status: "won",
    owner_id: "profile-2",
    created_at: "2024-03-08T08:00:00Z",
    owner: MOCK_PROFILES[1],
  },
  {
    id: "lead-6",
    workspace_id: "ws-1",
    name: "Camila Nunes",
    email: "camila@clinicazen.com",
    phone: "(62) 95544-3322",
    company: "Clínica Zen",
    role: "Gerente Administrativo",
    status: "lost",
    owner_id: "profile-1",
    created_at: "2024-03-05T16:00:00Z",
    owner: MOCK_PROFILES[0],
  },
  {
    id: "lead-7",
    workspace_id: "ws-1",
    name: "Henrique Gomes",
    email: "henrique@construvida.com",
    phone: "(85) 99933-2211",
    company: "Construvida",
    role: "VP de Operações",
    status: "new",
    owner_id: "profile-3",
    created_at: "2024-03-18T13:30:00Z",
    owner: MOCK_PROFILES[2],
  },
  {
    id: "lead-8",
    workspace_id: "ws-1",
    name: "Larissa Pinto",
    email: "larissa@edutechbr.com",
    phone: "(11) 97722-1100",
    company: "EduTech BR",
    role: "Diretora de Produto",
    status: "contact",
    owner_id: "profile-2",
    created_at: "2024-03-19T09:45:00Z",
    owner: MOCK_PROFILES[1],
  },
  {
    id: "lead-9",
    workspace_id: "ws-1",
    name: "Bruno Carvalho",
    email: "bruno@financepro.com.br",
    phone: "(61) 98811-0099",
    company: "FinancePro",
    role: "CFO",
    status: "proposal",
    owner_id: "profile-3",
    created_at: "2024-03-20T15:00:00Z",
    owner: MOCK_PROFILES[2],
  },
  {
    id: "lead-10",
    workspace_id: "ws-1",
    name: "Tatiana Ramos",
    email: "tatiana@healthplus.com",
    phone: "(71) 96600-8877",
    company: "HealthPlus",
    role: "Head de Marketing",
    status: "negotiation",
    owner_id: "profile-1",
    created_at: "2024-03-21T10:00:00Z",
    owner: MOCK_PROFILES[0],
  },
  {
    id: "lead-11",
    workspace_id: "ws-1",
    name: "Rodrigo Ferreira",
    email: "rodrigo@solartec.com.br",
    phone: "(19) 95599-7766",
    company: "SolarTec",
    role: "Engenheiro Sênior",
    status: "won",
    owner_id: "profile-3",
    created_at: "2024-03-03T12:00:00Z",
    owner: MOCK_PROFILES[2],
  },
  {
    id: "lead-12",
    workspace_id: "ws-1",
    name: "Priscila Barros",
    email: "priscila@varejo360.com",
    phone: "(27) 97788-5566",
    company: "Varejo 360",
    role: "Gerente de Vendas",
    status: "new",
    owner_id: "profile-2",
    created_at: "2024-03-22T08:30:00Z",
    owner: MOCK_PROFILES[1],
  },
]

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: "act-1",
    workspace_id: "ws-1",
    lead_id: "lead-1",
    type: "call",
    description: "Ligação inicial de apresentação. Lead demonstrou interesse no plano Pro.",
    author_id: "profile-1",
    activity_date: "2024-03-10T10:00:00Z",
    created_at: "2024-03-10T10:00:00Z",
    author: MOCK_PROFILES[0],
  },
  {
    id: "act-2",
    workspace_id: "ws-1",
    lead_id: "lead-1",
    type: "email",
    description: "Enviei o material institucional e case studies de clientes similares.",
    author_id: "profile-1",
    activity_date: "2024-03-11T14:30:00Z",
    created_at: "2024-03-11T14:30:00Z",
    author: MOCK_PROFILES[0],
  },
  {
    id: "act-3",
    workspace_id: "ws-1",
    lead_id: "lead-1",
    type: "meeting",
    description: "Reunião por vídeo com o time técnico da TechCorp. Apresentei a demo completa.",
    author_id: "profile-1",
    activity_date: "2024-03-13T16:00:00Z",
    created_at: "2024-03-13T16:00:00Z",
    author: MOCK_PROFILES[0],
  },
  {
    id: "act-4",
    workspace_id: "ws-1",
    lead_id: "lead-2",
    type: "call",
    description: "Primeiro contato. Juliana pediu para ligar na próxima semana.",
    author_id: "profile-2",
    activity_date: "2024-03-12T11:00:00Z",
    created_at: "2024-03-12T11:00:00Z",
    author: MOCK_PROFILES[1],
  },
  {
    id: "act-5",
    workspace_id: "ws-1",
    lead_id: "lead-2",
    type: "note",
    description: "Lead mencionou que está avaliando 3 concorrentes. Ponto de atenção: preço.",
    author_id: "profile-2",
    activity_date: "2024-03-14T09:00:00Z",
    created_at: "2024-03-14T09:00:00Z",
    author: MOCK_PROFILES[1],
  },
  {
    id: "act-6",
    workspace_id: "ws-1",
    lead_id: "lead-3",
    type: "email",
    description: "Enviei proposta comercial personalizada com desconto de 10% para contrato anual.",
    author_id: "profile-1",
    activity_date: "2024-03-15T10:00:00Z",
    created_at: "2024-03-15T10:00:00Z",
    author: MOCK_PROFILES[0],
  },
]
