import type { Lead, Activity, Profile, Deal } from "@/types"

export const MOCK_PROFILES: Profile[] = [
  {
    id: "profile-1",
    name: "Ana Souza",
    email: "ana@pipeflow.com",
    avatar_url: null,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "profile-2",
    name: "Carlos Lima",
    email: "carlos@pipeflow.com",
    avatar_url: null,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "profile-3",
    name: "Beatriz Rocha",
    email: "bea@pipeflow.com",
    avatar_url: null,
    created_at: "2024-01-01T00:00:00Z",
  },
]

export const MOCK_LEADS: Lead[] = [
  {
    id: "lead-1",
    workspace_id: "ws-1",
    name: "Rafael Mendes",
    email: "rafael@techcorp.com",
    phone: "(11) 98765-4321",
    company: "TechCorp",
    role: "CEO",
    status: "novo",
    owner_id: "profile-1",
    created_at: "2024-03-10T09:00:00Z",
    owner: MOCK_PROFILES[0],
  },
  {
    id: "lead-2",
    workspace_id: "ws-1",
    name: "Juliana Torres",
    email: "juliana@startupx.io",
    phone: "(21) 99887-6655",
    company: "StartupX",
    role: "CTO",
    status: "contato",
    owner_id: "profile-2",
    created_at: "2024-03-12T10:30:00Z",
    owner: MOCK_PROFILES[1],
  },
  {
    id: "lead-3",
    workspace_id: "ws-1",
    name: "Marcos Pereira",
    email: "marcos@consultoria.com.br",
    phone: "(31) 97654-3210",
    company: "Consultoria MP",
    role: "Diretor Comercial",
    status: "proposta",
    owner_id: "profile-1",
    created_at: "2024-03-14T14:00:00Z",
    owner: MOCK_PROFILES[0],
  },
  {
    id: "lead-4",
    workspace_id: "ws-1",
    name: "Fernanda Costa",
    email: "fernanda@agenciafoco.com",
    phone: "(41) 98877-5544",
    company: "Agência Foco",
    role: "Sócia-Fundadora",
    status: "negociacao",
    owner_id: "profile-3",
    created_at: "2024-03-15T11:00:00Z",
    owner: MOCK_PROFILES[2],
  },
  {
    id: "lead-5",
    workspace_id: "ws-1",
    name: "Diego Alves",
    email: "diego@logisticabr.com",
    phone: "(51) 96655-4433",
    company: "LogísticaBR",
    role: "Gerente de TI",
    status: "ganho",
    owner_id: "profile-2",
    created_at: "2024-03-08T08:00:00Z",
    owner: MOCK_PROFILES[1],
  },
  {
    id: "lead-6",
    workspace_id: "ws-1",
    name: "Camila Nunes",
    email: "camila@clinicazen.com",
    phone: "(62) 95544-3322",
    company: "Clínica Zen",
    role: "Gerente Administrativo",
    status: "perdido",
    owner_id: "profile-1",
    created_at: "2024-03-05T16:00:00Z",
    owner: MOCK_PROFILES[0],
  },
  {
    id: "lead-7",
    workspace_id: "ws-1",
    name: "Henrique Gomes",
    email: "henrique@construvida.com",
    phone: "(85) 99933-2211",
    company: "Construvida",
    role: "VP de Operações",
    status: "novo",
    owner_id: "profile-3",
    created_at: "2024-03-18T13:30:00Z",
    owner: MOCK_PROFILES[2],
  },
  {
    id: "lead-8",
    workspace_id: "ws-1",
    name: "Larissa Pinto",
    email: "larissa@edutechbr.com",
    phone: "(11) 97722-1100",
    company: "EduTech BR",
    role: "Diretora de Produto",
    status: "contato",
    owner_id: "profile-2",
    created_at: "2024-03-19T09:45:00Z",
    owner: MOCK_PROFILES[1],
  },
  {
    id: "lead-9",
    workspace_id: "ws-1",
    name: "Bruno Carvalho",
    email: "bruno@financepro.com.br",
    phone: "(61) 98811-0099",
    company: "FinancePro",
    role: "CFO",
    status: "proposta",
    owner_id: "profile-3",
    created_at: "2024-03-20T15:00:00Z",
    owner: MOCK_PROFILES[2],
  },
  {
    id: "lead-10",
    workspace_id: "ws-1",
    name: "Tatiana Ramos",
    email: "tatiana@healthplus.com",
    phone: "(71) 96600-8877",
    company: "HealthPlus",
    role: "Head de Marketing",
    status: "negociacao",
    owner_id: "profile-1",
    created_at: "2024-03-21T10:00:00Z",
    owner: MOCK_PROFILES[0],
  },
  {
    id: "lead-11",
    workspace_id: "ws-1",
    name: "Rodrigo Ferreira",
    email: "rodrigo@solartec.com.br",
    phone: "(19) 95599-7766",
    company: "SolarTec",
    role: "Engenheiro Sênior",
    status: "ganho",
    owner_id: "profile-3",
    created_at: "2024-03-03T12:00:00Z",
    owner: MOCK_PROFILES[2],
  },
  {
    id: "lead-12",
    workspace_id: "ws-1",
    name: "Priscila Barros",
    email: "priscila@varejo360.com",
    phone: "(27) 97788-5566",
    company: "Varejo 360",
    role: "Gerente de Vendas",
    status: "novo",
    owner_id: "profile-2",
    created_at: "2024-03-22T08:30:00Z",
    owner: MOCK_PROFILES[1],
  },
]

function daysFromNow(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return d.toISOString()
}

function daysAgo(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() - days)
  return d.toISOString()
}

export const MOCK_DEALS: Deal[] = [
  // novo_lead (3)
  {
    id: "deal-1",
    workspace_id: "ws-1",
    title: "Licença Enterprise TechCorp",
    value: 48000,
    stage: "novo_lead",
    lead_id: "lead-1",
    owner_id: "profile-1",
    due_date: daysFromNow(18),
    position: 0,
    created_at: daysAgo(49),
    lead: MOCK_LEADS[0],
    owner: MOCK_PROFILES[0],
  },
  {
    id: "deal-2",
    workspace_id: "ws-1",
    title: "Plano Pro — Construvida",
    value: 12000,
    stage: "novo_lead",
    lead_id: "lead-6",
    owner_id: "profile-3",
    due_date: daysFromNow(30),
    position: 1,
    created_at: daysAgo(41),
    lead: MOCK_LEADS[6],
    owner: MOCK_PROFILES[2],
  },
  {
    id: "deal-3",
    workspace_id: "ws-1",
    title: "Varejo 360 — Expansão de Equipe",
    value: 8400,
    stage: "novo_lead",
    lead_id: "lead-11",
    owner_id: "profile-2",
    due_date: null,
    position: 2,
    created_at: daysAgo(37),
    lead: MOCK_LEADS[11],
    owner: MOCK_PROFILES[1],
  },
  // contato_realizado (3)
  {
    id: "deal-4",
    workspace_id: "ws-1",
    title: "StartupX — Onboarding Time Técnico",
    value: 18500,
    stage: "contato_realizado",
    lead_id: "lead-1",
    owner_id: "profile-2",
    due_date: daysFromNow(5),
    position: 0,
    created_at: daysAgo(47),
    lead: MOCK_LEADS[1],
    owner: MOCK_PROFILES[1],
  },
  {
    id: "deal-5",
    workspace_id: "ws-1",
    title: "EduTech BR — Assinatura Anual",
    value: 22800,
    stage: "contato_realizado",
    lead_id: "lead-7",
    owner_id: "profile-2",
    due_date: daysFromNow(2),
    position: 1,
    created_at: daysAgo(40),
    lead: MOCK_LEADS[7],
    owner: MOCK_PROFILES[1],
  },
  {
    id: "deal-6",
    workspace_id: "ws-1",
    title: "LogísticaBR — Módulo Relatórios",
    value: 9600,
    stage: "contato_realizado",
    lead_id: "lead-4",
    owner_id: "profile-2",
    due_date: null,
    position: 2,
    created_at: daysAgo(61),
    lead: MOCK_LEADS[4],
    owner: MOCK_PROFILES[1],
  },
  // proposta_enviada (3)
  {
    id: "deal-7",
    workspace_id: "ws-1",
    title: "Consultoria MP — Plano Pro Anual",
    value: 35200,
    stage: "proposta_enviada",
    lead_id: "lead-2",
    owner_id: "profile-1",
    due_date: daysFromNow(7),
    position: 0,
    created_at: daysAgo(45),
    lead: MOCK_LEADS[2],
    owner: MOCK_PROFILES[0],
  },
  {
    id: "deal-8",
    workspace_id: "ws-1",
    title: "FinancePro — Integração API",
    value: 54000,
    stage: "proposta_enviada",
    lead_id: "lead-8",
    owner_id: "profile-3",
    due_date: daysFromNow(1),
    position: 1,
    created_at: daysAgo(39),
    lead: MOCK_LEADS[8],
    owner: MOCK_PROFILES[2],
  },
  {
    id: "deal-9",
    workspace_id: "ws-1",
    title: "HealthPlus — Dashboard Personalizado",
    value: 28000,
    stage: "proposta_enviada",
    lead_id: "lead-9",
    owner_id: "profile-1",
    due_date: daysFromNow(12),
    position: 2,
    created_at: daysAgo(38),
    lead: MOCK_LEADS[9],
    owner: MOCK_PROFILES[0],
  },
  // negociacao (3)
  {
    id: "deal-10",
    workspace_id: "ws-1",
    title: "Agência Foco — Contrato Semestral",
    value: 67500,
    stage: "negociacao",
    lead_id: "lead-3",
    owner_id: "profile-3",
    due_date: daysFromNow(3),
    position: 0,
    created_at: daysAgo(44),
    lead: MOCK_LEADS[3],
    owner: MOCK_PROFILES[2],
  },
  {
    id: "deal-11",
    workspace_id: "ws-1",
    title: "SolarTec — Suite Completa",
    value: 92000,
    stage: "negociacao",
    lead_id: "lead-10",
    owner_id: "profile-3",
    due_date: daysFromNow(6),
    position: 1,
    created_at: daysAgo(86),
    lead: MOCK_LEADS[10],
    owner: MOCK_PROFILES[2],
  },
  {
    id: "deal-12",
    workspace_id: "ws-1",
    title: "HealthPlus — Renovação + Upgrade",
    value: 38400,
    stage: "negociacao",
    lead_id: "lead-9",
    owner_id: "profile-1",
    due_date: daysFromNow(0),
    position: 2,
    created_at: daysAgo(38),
    lead: MOCK_LEADS[9],
    owner: MOCK_PROFILES[0],
  },
  // fechado_ganho (3)
  {
    id: "deal-13",
    workspace_id: "ws-1",
    title: "LogísticaBR — Licença Anual Pro",
    value: 28800,
    stage: "fechado_ganho",
    lead_id: "lead-4",
    owner_id: "profile-2",
    due_date: null,
    position: 0,
    created_at: daysAgo(58),
    lead: MOCK_LEADS[4],
    owner: MOCK_PROFILES[1],
  },
  {
    id: "deal-14",
    workspace_id: "ws-1",
    title: "SolarTec — Plano Pro 12 meses",
    value: 58800,
    stage: "fechado_ganho",
    lead_id: "lead-10",
    owner_id: "profile-3",
    due_date: null,
    position: 1,
    created_at: daysAgo(69),
    lead: MOCK_LEADS[10],
    owner: MOCK_PROFILES[2],
  },
  {
    id: "deal-15",
    workspace_id: "ws-1",
    title: "TechCorp — Piloto 30 dias → Conversão",
    value: 14400,
    stage: "fechado_ganho",
    lead_id: "lead-1",
    owner_id: "profile-1",
    due_date: null,
    position: 2,
    created_at: daysAgo(74),
    lead: MOCK_LEADS[0],
    owner: MOCK_PROFILES[0],
  },
  // fechado_perdido (3)
  {
    id: "deal-16",
    workspace_id: "ws-1",
    title: "Clínica Zen — Proposta Recusada",
    value: 7200,
    stage: "fechado_perdido",
    lead_id: "lead-5",
    owner_id: "profile-1",
    due_date: null,
    position: 0,
    created_at: daysAgo(54),
    lead: MOCK_LEADS[5],
    owner: MOCK_PROFILES[0],
  },
  {
    id: "deal-17",
    workspace_id: "ws-1",
    title: "EduTech BR — Perdeu para concorrente",
    value: 19200,
    stage: "fechado_perdido",
    lead_id: "lead-7",
    owner_id: "profile-2",
    due_date: null,
    position: 1,
    created_at: daysAgo(61),
    lead: MOCK_LEADS[7],
    owner: MOCK_PROFILES[1],
  },
  {
    id: "deal-18",
    workspace_id: "ws-1",
    title: "Varejo 360 — Budget insuficiente",
    value: 5400,
    stage: "fechado_perdido",
    lead_id: "lead-11",
    owner_id: "profile-2",
    due_date: null,
    position: 2,
    created_at: daysAgo(67),
    lead: MOCK_LEADS[11],
    owner: MOCK_PROFILES[1],
  },
]

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: "act-1",
    workspace_id: "ws-1",
    lead_id: "lead-1",
    type: "ligacao",
    description: "Ligação inicial de apresentação. Lead demonstrou interesse no plano Pro.",
    author_id: "profile-1",
    activity_date: "2024-03-10T10:00:00Z",
    created_at: "2024-03-10T10:00:00Z",
    author: MOCK_PROFILES[0],
  },
  {
    id: "act-2",
    workspace_id: "ws-1",
    lead_id: "lead-1",
    type: "email",
    description: "Enviei o material institucional e case studies de clientes similares.",
    author_id: "profile-1",
    activity_date: "2024-03-11T14:30:00Z",
    created_at: "2024-03-11T14:30:00Z",
    author: MOCK_PROFILES[0],
  },
  {
    id: "act-3",
    workspace_id: "ws-1",
    lead_id: "lead-1",
    type: "reuniao",
    description: "Reunião por vídeo com o time técnico da TechCorp. Apresentei a demo completa.",
    author_id: "profile-1",
    activity_date: "2024-03-13T16:00:00Z",
    created_at: "2024-03-13T16:00:00Z",
    author: MOCK_PROFILES[0],
  },
  {
    id: "act-4",
    workspace_id: "ws-1",
    lead_id: "lead-2",
    type: "ligacao",
    description: "Primeiro contato. Juliana pediu para ligar na próxima semana.",
    author_id: "profile-2",
    activity_date: "2024-03-12T11:00:00Z",
    created_at: "2024-03-12T11:00:00Z",
    author: MOCK_PROFILES[1],
  },
  {
    id: "act-5",
    workspace_id: "ws-1",
    lead_id: "lead-2",
    type: "nota",
    description: "Lead mencionou que está avaliando 3 concorrentes. Ponto de atenção: preço.",
    author_id: "profile-2",
    activity_date: "2024-03-14T09:00:00Z",
    created_at: "2024-03-14T09:00:00Z",
    author: MOCK_PROFILES[1],
  },
  {
    id: "act-6",
    workspace_id: "ws-1",
    lead_id: "lead-3",
    type: "email",
    description: "Enviei proposta comercial personalizada com desconto de 10% para contrato anual.",
    author_id: "profile-1",
    activity_date: "2024-03-15T10:00:00Z",
    created_at: "2024-03-15T10:00:00Z",
    author: MOCK_PROFILES[0],
  },
]
